-- TeachCode shared identity tables are intentionally not created or altered here.
CREATE TABLE IF NOT EXISTS cms_courses (
 id uuid PRIMARY KEY, slug text UNIQUE NOT NULL, title text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','archived')), created_by uuid NOT NULL REFERENCES profiles(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS cms_modules (
 id uuid PRIMARY KEY, course_id uuid NOT NULL REFERENCES cms_courses(id) ON DELETE CASCADE, title text NOT NULL, position integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(course_id,position));
CREATE TABLE IF NOT EXISTS cms_course_staff_assignments (course_id uuid NOT NULL REFERENCES cms_courses(id) ON DELETE CASCADE, profile_id uuid NOT NULL REFERENCES profiles(id), assigned_by uuid NOT NULL REFERENCES profiles(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(course_id,profile_id));
CREATE TABLE IF NOT EXISTS cms_lessons (
 id uuid PRIMARY KEY, course_id uuid NOT NULL REFERENCES cms_courses(id) ON DELETE CASCADE, module_id uuid REFERENCES cms_modules(id) ON DELETE SET NULL, slug text NOT NULL, title text NOT NULL, description text NOT NULL DEFAULT '', track text NOT NULL DEFAULT 'Python', level text NOT NULL DEFAULT 'year 1', mode text NOT NULL DEFAULT 'lesson', programming_language text, tags text[] NOT NULL DEFAULT '{}', presentation text NOT NULL DEFAULT 'guided', runtime_scope text NOT NULL DEFAULT 'per-step', draft_revision_id uuid, published_revision_id uuid, updated_by uuid NOT NULL REFERENCES profiles(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(course_id,slug));
CREATE TABLE IF NOT EXISTS cms_lesson_revisions (id uuid PRIMARY KEY, lesson_id uuid NOT NULL REFERENCES cms_lessons(id) ON DELETE CASCADE, revision_number integer NOT NULL, state text NOT NULL CHECK(state IN ('draft','published','superseded')), immutable boolean NOT NULL DEFAULT false, created_by uuid NOT NULL REFERENCES profiles(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(lesson_id,revision_number));
DO $$ BEGIN ALTER TABLE cms_lessons ADD CONSTRAINT cms_lessons_draft_fk FOREIGN KEY(draft_revision_id) REFERENCES cms_lesson_revisions(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE cms_lessons ADD CONSTRAINT cms_lessons_published_fk FOREIGN KEY(published_revision_id) REFERENCES cms_lesson_revisions(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS cms_lesson_steps (id uuid PRIMARY KEY, revision_id uuid NOT NULL REFERENCES cms_lesson_revisions(id) ON DELETE CASCADE, stable_key text NOT NULL, title text NOT NULL, position integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(revision_id,position));
CREATE TABLE IF NOT EXISTS cms_content_blocks (id uuid PRIMARY KEY, stable_id uuid NOT NULL, revision_id uuid NOT NULL REFERENCES cms_lesson_revisions(id) ON DELETE CASCADE, step_id uuid NOT NULL REFERENCES cms_lesson_steps(id) ON DELETE CASCADE, block_type text NOT NULL, position integer NOT NULL, visible boolean NOT NULL DEFAULT true, schema_version integer NOT NULL DEFAULT 1, created_by uuid REFERENCES profiles(id), updated_by uuid REFERENCES profiles(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE(revision_id,stable_id), UNIQUE(step_id,position));
-- Each typed table is separately evolvable. `payload` is a small extensibility envelope, not lesson content.
CREATE TABLE IF NOT EXISTS cms_rich_text_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, markdown text NOT NULL, schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_task_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, statement text NOT NULL, context text NOT NULL DEFAULT '', schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_function_references(id uuid PRIMARY KEY, task_block_id uuid NOT NULL REFERENCES cms_task_blocks(block_id) ON DELETE CASCADE, name text NOT NULL, summary text NOT NULL, position int NOT NULL);
CREATE TABLE IF NOT EXISTS cms_quick_reference_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, title text NOT NULL, markdown text NOT NULL, schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_worked_example_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, title text, language text NOT NULL, code text NOT NULL, explanation text NOT NULL DEFAULT '', runnable boolean NOT NULL DEFAULT false, expected_output text, schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_figure_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, image_url text NOT NULL, alt_text text NOT NULL, caption text, markdown text NOT NULL DEFAULT '', schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_mcq_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, question text NOT NULL, multiple boolean NOT NULL DEFAULT false, explanation text NOT NULL DEFAULT '', schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_mcq_options(id uuid PRIMARY KEY, mcq_block_id uuid NOT NULL REFERENCES cms_mcq_blocks(block_id) ON DELETE CASCADE, text text NOT NULL, is_correct boolean NOT NULL DEFAULT false, position int NOT NULL);
CREATE TABLE IF NOT EXISTS cms_code_exercise_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, language text NOT NULL, starter_code text NOT NULL, solution text, execution text NOT NULL DEFAULT 'browser', prompt text NOT NULL, check_script text, style_config jsonb NOT NULL DEFAULT '{}', randomisation jsonb NOT NULL DEFAULT '{}', review_principles text[] NOT NULL DEFAULT '{}', schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_reflection_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, prompt text NOT NULL, schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_reflection_rubrics(id uuid PRIMARY KEY, reflection_block_id uuid NOT NULL REFERENCES cms_reflection_blocks(block_id) ON DELETE CASCADE, key_ideas text[] NOT NULL DEFAULT '{}', misconceptions text[] NOT NULL DEFAULT '{}', acceptable_variants text[] NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS cms_tutor_config_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, mode text NOT NULL, chips text[] NOT NULL DEFAULT '{}', constraints text NOT NULL DEFAULT '', llm_allowed boolean NOT NULL DEFAULT false, copying_allowed boolean NOT NULL DEFAULT false, schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_data_asset_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, public_url text NOT NULL, filename text NOT NULL, runtime_path text, description text NOT NULL DEFAULT '', schema_version int NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS cms_code_review_blocks(block_id uuid PRIMARY KEY REFERENCES cms_content_blocks(id) ON DELETE CASCADE, title text NOT NULL, purpose text NOT NULL, mechanism text NOT NULL, output text NOT NULL, key_ideas text[] NOT NULL DEFAULT '{}', misconceptions text[] NOT NULL DEFAULT '{}', acceptable_variants text[] NOT NULL DEFAULT '{}', schema_version int NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS cms_blocks_revision_step_idx ON cms_content_blocks(revision_id,step_id,position) WHERE deleted_at IS NULL;
